// Тексты сайта на двух языках. Правила (CLAUDE.md): никаких выдуманных цифр,
// врачей и кейсов; никаких обещаний результата («безболезненно», «навсегда», «гарантия»).
// Каждое утверждение опирается на docs/brief.md, отзывы или посты клиники.

import type { Lang } from './site';

const es = {
  htmlLang: 'es-ES',
  meta: {
    title: 'Dentista en Valencia junto a Torres de Serranos | Smile House',
    description:
      'Clínica dental Smile House en Valencia, junto a las Torres de Serranos: limpieza, endodoncia, implantes, carillas, ortodoncia y casos complejos. Laboratorio propio, microscopio y escáner 3D. Atendemos en español y ruso.',
  },
  nav: {
    cases: 'Casos',
    visit: 'Primera visita',
    team: 'Equipo',
    services: 'Tratamientos',
    reviews: 'Opiniones',
    contact: 'Contacto',
    menu: 'Menú',
    close: 'Cerrar',
    langSwitch: 'Русский',
    langSwitchShort: 'RU',
  },
  cta: {
    book: 'Pedir cita',
    call: 'Llamar',
    whatsapp: 'WhatsApp',
  },
  status: {
    open: 'Abierto ahora',
    openUntil: (t: string) => `hasta las ${t}`,
    closed: 'Cerrado ahora',
    opensAt: (day: string, t: string) => `Abrimos ${day} a las ${t}`,
    today: 'hoy',
    tomorrow: 'mañana',
    days: ['el domingo', 'el lunes', 'el martes', 'el miércoles', 'el jueves', 'el viernes', 'el sábado'],
    leaveRequest: 'Déjanos tu teléfono y te llamamos.',
  },
  hero: {
    eyebrow: 'Clínica dental en Valencia · desde 2018',
    titleBefore: 'Toda la odontología ',
    titleMark: 'en una sola\u00A0clínica',
    titleAfter: ' en el centro de Valencia.',
    lead: 'De la limpieza y las caries a los implantes, las carillas y la ortodoncia. Laboratorio dental propio, microscopio y escáner 3D. Antes de empezar, te lo enseñamos en la imagen y te decimos el precio.',
    rating: (v: string, c: number) => `${v} en Google · ${c} opiniones`,
    quoteLabel: 'Opinión en Google',
    reviewsLabel: 'Opiniones de pacientes',
    langs: 'Atendemos en español y ruso',
    servicesLabel: 'Tratamientos',
    services: [
      { label: 'Implantes', href: '#tratamientos' },
      { label: 'Carillas', href: '#tratamientos' },
      { label: 'Muelas del juicio', href: '#tratamientos' },
      { label: 'Endodoncia', href: '#tratamientos' },
      { label: 'Ortodoncia', href: '#tratamientos' },
      { label: 'Limpieza y blanqueamiento', href: '#tratamientos' },
      { label: 'Dolor agudo', href: '#cita' },
    ],
    facts: [
      { icon: 'tooth', title: 'Laboratorio propio', text: 'La cerámica se pinta a mano en la clínica' },
      { icon: 'microscope', title: 'Microscopio', text: 'Endodoncia y detalle bajo aumento' },
      { icon: 'scan', title: 'Escáner 3D', text: 'Protocolo digital de principio a fin' },
      { icon: 'translate', title: 'Español y ruso', text: 'También te escribimos en inglés y ucraniano' },
    ],
    resultsLink: 'Ver antes y después',
  },
  results: {
    title: 'Antes y después',
    lead: 'Trabajos de la clínica tal como los publicó en Instagram: carillas, rehabilitaciones completas, coronas. Arrastra la línea para comparar.',
    open: 'Ver en Instagram',
    moreTitle: 'Más trabajos en Instagram',
    moreLead: 'Estas fotos las carga Instagram (Meta) solo si lo pides; Instagram puede usar cookies.',
    load: 'Mostrar las fotos',
    all: 'Todo el Instagram de la clínica',
  },
  cases: {
    title: 'Casos que no todos aceptan',
    lead: 'Cuando en otra clínica te dijeron que no o el tratamiento salió mal. Así explican los doctores estos casos en Instagram, con fotos de la propia clínica.',
    quoteFrom: 'Opinión de',
    open: 'Ver el caso en Instagram',
    before: 'Antes',
    after: 'Después',
    handle: 'Comparar antes y después',
  },
  visit: {
    title: 'Primero te lo explicamos. Después tratamos.',
    lead: 'De la primera visita sales con un diagnóstico claro, un plan y un precio.',
    steps: [
      {
        title: 'Nos cuentas qué te pasa',
        text: 'Por teléfono, WhatsApp o con el formulario. Si tienes dolor, dínoslo al llamar.',
      },
      {
        title: 'Lo miramos y te lo enseñamos',
        text: 'Exploración, radiografías y escáner 3D. Te enseñamos en la imagen qué ocurre, no solo el diagnóstico.',
      },
      {
        title: 'Plan y precio antes de empezar',
        text: 'Te explicamos las opciones, la diferencia entre materiales y marcas, y cuánto cuesta.',
      },
      {
        title: 'Empezamos cuando estés listo',
        text: 'Sin prisas y sin dudas pendientes. La decisión es tuya.',
      },
    ],
    equipmentTitle: 'Con qué trabajamos',
    photoAlt: 'Un doctor de Smile House con un paciente en consulta',
    equipment: [
      { icon: 'microscope', label: 'Microscopio dental', photo: 'eq-microscope' },
      { icon: 'scan', label: 'Escáner 3D', photo: 'eq-scanner' },
      { icon: 'cube', label: 'Protocolo digital completo', photo: 'eq-digital' },
      { icon: 'tooth', label: 'Laboratorio dental propio', photo: 'eq-lab' },
    ],
  },
  team: {
    title: 'El equipo',
    lead: 'Doctores que los pacientes mencionan por su nombre en las opiniones de Google.',
    reviewFrom: 'Opinión de',
    microscopeAlt: 'Doctor y asistente de Smile House trabajando con microscopio',
    harvardAlt: 'Doctores de Smile House en un congreso en Harvard School of Dental Medicine',
    talksTitle: 'Los doctores presentan casos en congresos profesionales.',
    groupAlt: 'Equipo de Smile House en la clínica',
    groupCaption: 'El equipo de Smile House. Foto de la ficha de la clínica en Google.',
    entranceAlt: 'Entrada de la clínica Smile House en la calle de la Visitació',
    operatoryAlt: 'Gabinete de Smile House con microscopio dental',
    harvardCaption: 'Harvard School of Dental Medicine, Boston. Foto publicada por la clínica.',
  },
  services: {
    title: 'Tratamientos',
    lead: 'Todo lo que hace la clínica, de la limpieza a los implantes. En cada punto, la publicación donde los doctores lo explican.',
    postLabel: 'Leer en Instagram',
    urgent: {
      title: 'Dolor agudo',
      text: 'Llama o escribe: te decimos cuándo podemos verte. Si es urgente, dilo al llamar.',
    },
  },
  reels: {
    title: 'Un día en Smile House',
    lead: 'Vídeos de la clínica: microscopio, escáner, manos y cuidado en cada detalle.',
    alt: 'Vídeo de trabajo en Smile House',
    play: 'Reproducir',
  },
  stories: {
    title: 'Pacientes que llegaron de otra clínica',
    lead: 'Dos pacientes cuentan en vídeo su historia. Hablan en ruso.',
    labels: ['Pasó por varias clínicas sin encontrar ayuda', 'Un tratamiento fallido en otra clínica'],
    play: 'Ver el vídeo con sonido',
    open: 'Ver en Instagram',
  },
  reviews: {
    title: 'Lo que dicen los pacientes',
    lead: 'Citas literales de las opiniones en Google Maps.',
    all: 'Todas las opiniones en Google',
    more: 'Ver más opiniones',
    less: 'Ver menos',
    count: (n: number) => `${n} opiniones`,
  },
  contact: {
    title: 'Cómo llegar',
    near: 'Junto a las Torres de Serranos. Hay parking cerca y se llega andando desde el centro.',
    hoursTitle: 'Horario',
    hours: [
      { d: 'Lunes a viernes', h: '10:00 - 16:30' },
      { d: 'Sábado y domingo', h: 'Cerrado' },
    ],
    route: 'Cómo llegar en Google Maps',
    mapConsent: 'El mapa lo carga Google y puede usar cookies.',
    mapShow: 'Mostrar el mapa',
    dmLangs: 'Escríbenos en español, inglés, ucraniano o ruso.',
  },
  form: {
    title: 'Pide tu cita',
    lead: 'Déjanos tu teléfono y te llamamos en horario de clínica: lunes a viernes, de 10:00 a 16:30.',
    name: 'Nombre',
    phone: 'Teléfono',
    phoneHint: 'Con prefijo si no es español',
    contactBy: '¿Cómo prefieres que te contactemos?',
    byCall: 'Llamada',
    byWhatsapp: 'WhatsApp',
    reason: 'Motivo (opcional)',
    reasonPlaceholder: 'Elige una opción',
    reasons: [
      'Dolor agudo',
      'Primera consulta',
      'Implantes',
      'Muela del juicio o extracción',
      'Carillas o estética',
      'Endodoncia',
      'Ortodoncia',
      'Limpieza o blanqueamiento',
      'Otro',
    ],
    consent: 'Acepto que Smile House use mis datos para contactarme sobre la cita.',
    privacy: 'Política de privacidad',
    submit: 'Enviar por WhatsApp',
    sending: 'Enviando…',
    okTitle: 'Abrimos WhatsApp.',
    okText: 'Envía el mensaje que hemos preparado y te respondemos en horario de clínica. Si es urgente, llámanos:',
    errText: 'No se ha podido enviar. Llámanos o escríbenos por WhatsApp:',
    errPhone: 'Revisa el teléfono: faltan cifras.',
    errName: 'Escribe tu nombre.',
    errConsent: 'Necesitamos tu consentimiento para llamarte.',
  },
  footer: {
    registro: 'Nº Registro Sanitario',
    registroPending: 'pendiente de confirmar',
    legal: 'Aviso legal y privacidad',
    cookies: 'Cookies',
    since: 'Desde 2018',
    madeBy: 'Web: 2BRO.LAB',
  },
  cookie: {
    text: 'No usamos cookies de publicidad ni de analítica. El mapa de Google solo se carga si lo permites.',
    accept: 'Permitir mapa',
    reject: 'Solo necesarias',
    more: 'Más información',
  },
};

type Copy = typeof es;

const ru: Copy = {
  htmlLang: 'ru-RU',
  meta: {
    title: 'Стоматолог в Валенсии, говорим по-русски | Smile House',
    description:
      'Стоматология Smile House в Валенсии, рядом с Torres de Serranos: чистка, лечение каналов, импланты, виниры, ортодонтия и сложные случаи. Своя лаборатория, микроскоп и 3D-сканер. Принимаем на русском и испанском.',
  },
  nav: {
    cases: 'Случаи',
    visit: 'Первый визит',
    team: 'Врачи',
    services: 'Лечение',
    reviews: 'Отзывы',
    contact: 'Контакты',
    menu: 'Меню',
    close: 'Закрыть',
    langSwitch: 'Español',
    langSwitchShort: 'ES',
  },
  cta: {
    book: 'Записаться',
    call: 'Позвонить',
    whatsapp: 'WhatsApp',
  },
  status: {
    open: 'Сейчас открыто',
    openUntil: (t: string) => `до ${t}`,
    closed: 'Сейчас закрыто',
    opensAt: (day: string, t: string) => `Откроемся ${day} в ${t}`,
    today: 'сегодня',
    tomorrow: 'завтра',
    days: ['в воскресенье', 'в понедельник', 'во вторник', 'в среду', 'в четверг', 'в пятницу', 'в субботу'],
    leaveRequest: 'Оставьте телефон, и мы перезвоним.',
  },
  hero: {
    eyebrow: 'Стоматология в Валенсии · с 2018 года',
    titleBefore: 'Вся стоматология ',
    titleMark: 'в\u00A0одной клинике',
    titleAfter: ' в центре Валенсии.',
    lead: 'От профчистки и кариеса до имплантов, виниров и ортодонтии. Своя зуботехническая лаборатория, микроскоп и 3D-сканер. До начала лечения показываем всё на снимке и называем цену.',
    rating: (v: string, c: number) => `${v} в Google · ${c} отзывов`,
    quoteLabel: 'Отзыв на Google',
    reviewsLabel: 'Отзывы пациентов',
    langs: 'Принимаем на русском и испанском',
    servicesLabel: 'Лечение',
    services: [
      { label: 'Импланты', href: '#tratamientos' },
      { label: 'Виниры', href: '#tratamientos' },
      { label: 'Зубы мудрости', href: '#tratamientos' },
      { label: 'Лечение каналов', href: '#tratamientos' },
      { label: 'Ортодонтия', href: '#tratamientos' },
      { label: 'Чистка и отбеливание', href: '#tratamientos' },
      { label: 'Острая боль', href: '#cita' },
    ],
    facts: [
      { icon: 'tooth', title: 'Своя лаборатория', text: 'Керамику расписывают вручную в клинике' },
      { icon: 'microscope', title: 'Микроскоп', text: 'Каналы и мелкие детали под увеличением' },
      { icon: 'scan', title: '3D-сканер', text: 'Цифровой протокол от начала до конца' },
      { icon: 'translate', title: 'Русский и испанский', text: 'Пишите и на украинском или английском' },
    ],
    resultsLink: 'Смотреть до и после',
  },
  results: {
    title: 'До и после',
    lead: 'Работы клиники — так, как она публикует их в Instagram: виниры, тотальные реставрации, коронки. Потяните линию, чтобы сравнить.',
    open: 'Смотреть в Instagram',
    moreTitle: 'Ещё работы в Instagram',
    moreLead: 'Эти фото загружает Instagram (Meta), и только по вашей кнопке; Instagram может использовать cookies.',
    load: 'Показать фото',
    all: 'Весь Instagram клиники',
  },
  cases: {
    title: 'Случаи, за которые берутся не все',
    lead: 'Когда в другой клинике отказали или лечение не получилось. Так врачи разбирают такие случаи в Instagram — с фото самой клиники.',
    quoteFrom: 'Отзыв',
    open: 'Смотреть случай в Instagram',
    before: 'До',
    after: 'После',
    handle: 'Сравнить до и после',
  },
  visit: {
    title: 'Сначала объясняем. Потом лечим.',
    lead: 'С первого визита вы уходите с понятным диагнозом, планом и ценой.',
    steps: [
      {
        title: 'Рассказываете, что беспокоит',
        text: 'По телефону, в WhatsApp или через заявку на сайте. Если болит, скажите об этом сразу.',
      },
      {
        title: 'Смотрим и показываем',
        text: 'Осмотр, снимки и 3D-скан. Показываем на снимке, что происходит, а не просто называем диагноз.',
      },
      {
        title: 'План и цена до начала',
        text: 'Объясняем варианты, разницу между материалами и марками и называем стоимость.',
      },
      {
        title: 'Начинаем, когда вы готовы',
        text: 'Без спешки и без оставшихся вопросов. Решение за вами.',
      },
    ],
    equipmentTitle: 'С чем работаем',
    photoAlt: 'Врач Smile House на приёме с пациентом',
    equipment: [
      { icon: 'microscope', label: 'Стоматологический микроскоп', photo: 'eq-microscope' },
      { icon: 'scan', label: '3D-сканер', photo: 'eq-scanner' },
      { icon: 'cube', label: 'Цифровой протокол от начала до конца', photo: 'eq-digital' },
      { icon: 'tooth', label: 'Своя зуботехническая лаборатория', photo: 'eq-lab' },
    ],
  },
  team: {
    title: 'Врачи',
    lead: 'Те, кого пациенты называют по имени в отзывах на Google.',
    reviewFrom: 'Отзыв',
    microscopeAlt: 'Врач и ассистент Smile House работают с микроскопом',
    harvardAlt: 'Врачи Smile House на конференции в Harvard School of Dental Medicine',
    talksTitle: 'Врачи клиники выступают с разборами случаев на профессиональных конференциях.',
    groupAlt: 'Команда Smile House в клинике',
    groupCaption: 'Команда Smile House. Фото из карточки клиники в Google.',
    entranceAlt: 'Вход в клинику Smile House на улице Visitació',
    operatoryAlt: 'Кабинет Smile House с микроскопом',
    harvardCaption: 'Harvard School of Dental Medicine, Бостон. Фото опубликовано клиникой.',
  },
  services: {
    title: 'Чем занимаемся',
    lead: 'Всё, что делают в клинике, — от чистки до имплантов. У каждого пункта — пост, где врачи это объясняют.',
    postLabel: 'Читать в Instagram',
    urgent: {
      title: 'Острая боль',
      text: 'Позвоните или напишите: скажем, когда сможем принять. Если срочно, скажите об этом сразу.',
    },
  },
  reels: {
    title: 'Один день в Smile House',
    lead: 'Видео из клиники: микроскоп, сканер, руки и внимание к каждой детали.',
    alt: 'Видео о работе Smile House',
    play: 'Воспроизвести',
  },
  stories: {
    title: 'Пациентки, которые пришли из других клиник',
    lead: 'Две истории — от первого лица, на видео.',
    labels: ['Прошла разные клиники, но помощи не получила', 'Некачественное лечение в другой клинике'],
    play: 'Смотреть видео со звуком',
    open: 'Смотреть в Instagram',
  },
  reviews: {
    title: 'Что пишут пациенты',
    lead: 'Цитаты из отзывов на Google Maps, дословно.',
    all: 'Все отзывы на Google',
    more: 'Показать ещё отзывы',
    less: 'Свернуть',
    count: (n: number) => `${n} отзывов`,
  },
  contact: {
    title: 'Как добраться',
    near: 'Рядом с Torres de Serranos. Неподалёку есть парковка, до центра можно дойти пешком.',
    hoursTitle: 'Часы работы',
    hours: [
      { d: 'Понедельник - пятница', h: '10:00 - 16:30' },
      { d: 'Суббота и воскресенье', h: 'Выходной' },
    ],
    route: 'Маршрут в Google Maps',
    mapConsent: 'Карту загружает Google, он может использовать cookies.',
    mapShow: 'Показать карту',
    dmLangs: 'Пишите на русском, украинском, испанском или английском.',
  },
  form: {
    title: 'Записаться на приём',
    lead: 'Оставьте телефон, и администратор перезвонит в рабочее время: понедельник - пятница, с 10:00 до 16:30.',
    name: 'Имя',
    phone: 'Телефон',
    phoneHint: 'С кодом страны, если номер не испанский',
    contactBy: 'Как удобнее связаться?',
    byCall: 'Звонок',
    byWhatsapp: 'WhatsApp',
    reason: 'Что беспокоит (необязательно)',
    reasonPlaceholder: 'Выберите вариант',
    reasons: [
      'Острая боль',
      'Первая консультация',
      'Импланты',
      'Зуб мудрости или удаление',
      'Виниры и эстетика',
      'Лечение каналов',
      'Ортодонтия',
      'Чистка или отбеливание',
      'Другое',
    ],
    consent: 'Я согласен(на), что Smile House использует мои данные только для того, чтобы связаться со мной по записи.',
    privacy: 'Политика конфиденциальности',
    submit: 'Отправить в WhatsApp',
    sending: 'Отправляем…',
    okTitle: 'Открыли WhatsApp.',
    okText: 'Отправьте готовое сообщение — ответим в рабочее время. Если срочно, звоните:',
    errText: 'Не получилось отправить. Позвоните нам или напишите в WhatsApp:',
    errPhone: 'Проверьте телефон: не хватает цифр.',
    errName: 'Напишите, как к вам обращаться.',
    errConsent: 'Без согласия мы не сможем вам перезвонить.',
  },
  footer: {
    registro: 'Nº Registro Sanitario',
    registroPending: 'уточняется',
    legal: 'Правовая информация',
    cookies: 'Cookies',
    since: 'С 2018 года',
    madeBy: 'Сайт: 2BRO.LAB',
  },
  cookie: {
    text: 'Мы не используем рекламные и аналитические cookies. Карта Google загружается, только если вы разрешите.',
    accept: 'Разрешить карту',
    reject: 'Только необходимые',
    more: 'Подробнее',
  },
};

export const copy: Record<Lang, Copy> = { es, ru };
