// Тексты сайта: es (основной), ru, en.
// Правила (CLAUDE.md): ни одной выдуманной цифры, врача или кейса; никаких
// обещаний результата («безболезненно», «навсегда», «гарантия»). Каждое
// утверждение опирается на materials/BRIEF.md, отзывы или посты клиники.
// Цифры случая 2,5 мм — из поста клиники DVt_z_YDooL (10.03.2026).

const IG = 'https://www.instagram.com/p/';

export const content = {
  es: {
    htmlLang: 'es-ES',
    ogLocale: 'es_ES',
    path: '/',
    meta: {
      title: 'Dentista en Valencia para casos complejos | Smile House',
      description:
        'Clínica dental Smile House, junto a Torres de Serranos. Implantes con poco hueso, muelas del juicio difíciles, carillas y rehabilitaciones. Te lo explicamos en la imagen antes de empezar. Español, ruso e inglés.',
    },
    langName: 'Español',
    skip: 'Saltar al contenido',
    nav: { cases: 'Casos', visit: 'Primera visita', team: 'Equipo', reviews: 'Opiniones', contact: 'Cómo llegar', menu: 'Menú', close: 'Cerrar' },
    cta: { book: 'Pedir cita', whatsapp: 'WhatsApp', call: 'Llamar' },
    status: {
      open: 'Abierto', until: 'hasta las', closed: 'Cerrado', opens: 'abre',
      today: 'hoy', tomorrow: 'mañana',
      days: ['el domingo', 'el lunes', 'el martes', 'el miércoles', 'el jueves', 'el viernes', 'el sábado'],
      at: 'a las',
    },
    hero: {
      h1: ['Los casos que ', 'otras clínicas derivan', ', aquí los tratamos.'],
      lead: 'Implantes con poco hueso, muelas del juicio complicadas, sonrisas completas por rehacer. Antes de tocar nada, te lo enseñamos en la imagen y te lo explicamos.',
      place: 'Valencia · junto a Torres de Serranos · desde 2018',
      langs: 'Atendemos en español, ruso e inglés',
      startLabel: '¿Qué te pasa?',
      photoAlt: 'Cirujano de Smile House con lupas y luz frontal, trabajando',
    },
    voices: {
      title: 'Lo que cuentan quienes llegan de otra clínica',
      ids: ['shein', 'bynkalo', 'khairova', 'pod'],
    },
    caseFile: {
      title: 'Un implante de 10 mm donde quedaban 2,5 mm de hueso',
      lead: 'Así explican los doctores sus casos. Este lo publicaron en Instagram con sus propias tomografías.',
      steps: [
        { mm: '2,5', title: 'Lo que había', text: 'Bajo el seno maxilar, en la zona del segundo molar superior, quedaban 2,5 mm de hueso. Con eso, el implante se apoyaría en el hueso solo en una cuarta parte de su longitud.' },
        { mm: '7,5', title: 'Lo que había que ganar', text: 'Para un implante de 10 mm hay que elevar el suelo del seno 7,5 mm sin romper la membrana que lo recubre. Los doctores lo llaman elevación de seno extrema.' },
        { mm: '10', title: 'Lo que se hizo', text: 'Implante de 10 mm colocado. Es el tipo de caso que se planifica sobre tomografía antes de abrir, y que se explica al paciente sobre la misma imagen.' },
      ],
      before: 'Tomografía antes', after: 'Tomografía después',
      unit: 'mm de hueso', source: 'Ver el caso en Instagram', url: IG + 'DVt_z_YDooL/',
    },
    ba: {
      title: 'Antes y después',
      lead: 'Fotos publicadas por la clínica. Arrastra la línea para comparar.',
      before: 'Antes', after: 'Después', handle: 'Comparar antes y después',
      cases: [
        { id: 'wear', label: 'Desgaste severo', note: 'Con un desgaste así no basta con poner carillas: hay que rediseñar cómo cierran los maxilares y elegir un material que aguante la carga.', url: IG + 'DVWPIBHDI9u/' },
        { id: 'metal', label: 'Coronas metálicas y huecos', note: 'Faltaban dientes y había restauraciones metálicas. Tras el diagnóstico y el plan: carillas, forma, simetría y color natural.', url: IG + 'DQt68YPDfVY/' },
      ],
      open: 'Ver en Instagram',
    },
    visit: {
      title: ['Primero te lo ', 'explicamos', '. Después tratamos.'],
      lead: 'De la primera visita sales con un diagnóstico claro, un plan y un precio. La decisión es tuya.',
      steps: [
        { t: 'Nos cuentas qué te pasa', d: 'Por WhatsApp, por teléfono o desde esta web, a cualquier hora. Si te duele, dínoslo.' },
        { t: 'Lo miramos y te lo enseñamos', d: 'Exploración, radiografía o tomografía y escáner 3D. Ves en la pantalla lo que vemos nosotros.' },
        { t: 'Plan y precio antes de empezar', d: 'Las opciones, la diferencia entre materiales y cuánto cuesta cada una.' },
        { t: 'Empezamos cuando estés listo', d: 'Sin prisas y sin dudas pendientes.' },
      ],
      quotes: ['iglesia', 'anders', 'garcia'],
      photoAlt: 'Doctor de Smile House hablando con un paciente en el sillón',
    },
    lens: {
      title: 'Bajo aumento',
      lead: 'Lo que los pacientes ven en la consulta y mencionan en sus opiniones.',
      items: [
        { img: 'eyepiece', t: 'Microscopio dental', d: 'Para conductos y restauraciones donde a simple vista no se ve.' },
        { img: 'scanner', t: 'Escáner 3D', d: 'Tu boca en la pantalla en minutos, sin pastas de impresión.' },
        { img: 'lab', t: 'Laboratorio propio', d: 'Cerámica, zirconio y disilicato de litio. Los efectos se pintan a mano.' },
        { img: 'xray', t: 'Planificación sobre imagen', d: 'Radiografías y tomografías antes de cada cirugía.' },
      ],
      harvard: { t: 'Casos presentados en Harvard', d: 'El equipo presentó sus casos en la Harvard School of Dental Medicine (Boston) en junio de 2026.', alt: 'Equipo de Smile House en la Harvard School of Dental Medicine' },
    },
    team: {
      title: 'Quién te atiende',
      lead: 'Los doctores que los pacientes nombran en sus opiniones de Google.',
      doctors: [
        { id: 'dmitry', name: 'Dr. Dmitry', role: 'Cirugía oral, implantes, muelas del juicio', review: 'shein' },
        { id: 'javier', name: 'Dr. Javier', role: 'Endodoncia', review: 'iglesia' },
        { id: 'lucila', name: 'Dra. Lucila', role: 'Odontología general', review: 'magris' },
      ],
      photoAlt: 'Doctor y asistente de Smile House trabajando con el microscopio',
    },
    services: {
      title: 'Tratamientos',
      lead: 'Precio tras la consulta, por escrito y antes de empezar.',
      consult: 'Precio en consulta',
      book: 'Pedir cita',
      items: [
        { key: 'implant', t: 'Implantes y elevación de seno', d: 'También con poco hueso. Planificación sobre tomografía.' },
        { key: 'wisdom', t: 'Muelas del juicio y extracciones complejas', d: 'Inclinadas, cerca del nervio, las que otros prefirieron no extraer.' },
        { key: 'veneers', t: 'Carillas, coronas, rehabilitaciones', d: 'Cerámica, zirconio y disilicato de litio, de nuestro laboratorio.' },
        { key: 'endo', t: 'Endodoncia con microscopio', d: 'Tratamiento de conductos, también repetición de tratamientos.' },
        { key: 'ortho', t: 'Ortodoncia', d: 'Brackets, alineadores y férulas.' },
        { key: 'hygiene', t: 'Higiene y blanqueamiento', d: 'Limpieza profesional, blanqueamiento en clínica o en casa.' },
        { key: 'urgent', t: 'Dolor agudo', d: 'Escríbenos y dinos que te duele: te decimos cuándo podemos verte.' },
      ],
    },
    reviews: {
      title: 'En palabras de los pacientes',
      lead: 'Citas literales de las opiniones en Google Maps.',
      all: 'Todas las opiniones en Google',
      ids: ['daniel', 'fatyuk', 'cotua', 'almudena', 'rl', 'barrera', 'medina', 'garcia'],
      source: 'Google',
    },
    faq: {
      title: 'Lo que suele preocupar',
      items: [
        { q: '¿Cuánto cuesta?', a: 'Depende del caso, por eso no publicamos tarifas cerradas. En la primera visita te damos el plan con el precio de cada opción, antes de empezar ningún tratamiento.' },
        { q: 'Tengo dolor ahora. ¿Me podéis ver pronto?', a: 'Escríbenos por WhatsApp o pide cita marcando «Tengo dolor». Te decimos cuándo podemos verte. Pacientes con dolor agudo cuentan en Google que les atendieron al día siguiente.' },
        { q: 'Me da miedo el dentista.', a: 'Es de lo que más hablan las opiniones. Antes de empezar te explicamos qué vamos a hacer y por qué, y no se empieza hasta que lo tengas claro.' },
        { q: 'Otra clínica me dijo que mi caso no tiene solución.', a: 'Trae tus radiografías o tomografías si las tienes. Lo miramos y te decimos con franqueza qué se puede hacer y qué no.' },
        { q: '¿Puedo pedir cita con un doctor concreto?', a: 'Sí, indícalo al pedir cita y te confirmamos con quién es la visita.' },
        { q: '¿En qué idiomas atendéis?', a: 'Español, ruso e inglés.' },
        { q: '¿Dónde aparco?', a: 'Hay parking cerca de la clínica, y desde el centro se llega andando cruzando Torres de Serranos.' },
      ],
    },
    contact: {
      title: 'Junto a Torres de Serranos',
      near: 'Al otro lado del puente, en La Zaidía. Hay parking cerca y desde el centro se llega andando.',
      hoursTitle: 'Horario', weekdays: 'Lunes a viernes', weekend: 'Sábado y domingo', closedWord: 'Cerrado',
      offHours: 'Fuera de horario, escríbenos: lo vemos al abrir.',
      route: 'Cómo llegar', mapShow: 'Mostrar el mapa', mapConsent: 'El mapa lo carga Google y puede usar cookies.',
    },
    booking: {
      title: 'Pedir cita',
      lead: 'Elige lo que encaje. Se abre WhatsApp con el mensaje listo; solo tienes que enviarlo.',
      reason: 'Motivo', day: 'Día que te va bien', time: 'Franja', doctor: 'Doctor', name: 'Tu nombre', note: 'Algo más (opcional)',
      notePh: 'Por ejemplo: tengo una tomografía de otra clínica',
      reasons: [
        { k: 'urgent', l: 'Tengo dolor' }, { k: 'checkup', l: 'Primera consulta' }, { k: 'implant', l: 'Implante' },
        { k: 'wisdom', l: 'Muela del juicio' }, { k: 'veneers', l: 'Carillas o estética' }, { k: 'endo', l: 'Endodoncia' },
        { k: 'ortho', l: 'Ortodoncia' }, { k: 'hygiene', l: 'Limpieza o blanqueamiento' },
      ],
      anyDay: 'Cualquier día', asap: 'Lo antes posible',
      times: [{ k: 'm', l: '10:00–12:00' }, { k: 'n', l: '12:00–14:00' }, { k: 'a', l: '14:00–16:30' }, { k: 'x', l: 'Me da igual' }],
      anyDoctor: 'Cualquiera',
      consent: 'Acepto que Smile House use estos datos para darme cita.',
      privacy: 'Privacidad',
      send: 'Enviar por WhatsApp', orCall: 'o llama al',
      errReason: 'Elige un motivo.', errName: 'Escribe tu nombre.', errConsent: 'Marca la casilla para continuar.',
      msg: { hello: 'Hola, quiero pedir cita en Smile House.', reason: 'Motivo', day: 'Día', time: 'Franja', doctor: 'Doctor', name: 'Nombre', note: 'Nota', lang: 'Idioma', langVal: 'español' },
      weekdayShort: ['dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb'],
      months: ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic'],
    },
    footer: {
      since: 'Clínica dental en Valencia desde 2018',
      registro: 'Nº Registro Sanitario', registroPending: 'pendiente',
      legal: 'Aviso legal y privacidad', cookies: 'Cookies', madeBy: 'Web: 2BRO.LAB',
    },
    cookie: { text: 'Sin cookies de publicidad ni de analítica. El mapa de Google solo se carga si lo permites.', accept: 'Permitir mapa', reject: 'Solo necesarias', more: 'Más información' },
    translated: 'Traducción',
  },

  ru: {
    htmlLang: 'ru',
    ogLocale: 'ru_RU',
    path: '/ru/',
    meta: {
      title: 'Стоматолог в Валенсии для сложных случаев | Smile House',
      description:
        'Стоматология Smile House у Torres de Serranos. Импланты при нехватке кости, сложные восьмёрки, виниры и восстановление улыбки. Сначала показываем на снимке и объясняем. Говорим по-русски.',
    },
    langName: 'Русский',
    skip: 'К содержанию',
    nav: { cases: 'Случаи', visit: 'Первый визит', team: 'Врачи', reviews: 'Отзывы', contact: 'Как добраться', menu: 'Меню', close: 'Закрыть' },
    cta: { book: 'Записаться', whatsapp: 'WhatsApp', call: 'Позвонить' },
    status: {
      open: 'Открыто', until: 'до', closed: 'Закрыто', opens: 'откроемся',
      today: 'сегодня', tomorrow: 'завтра',
      days: ['в воскресенье', 'в понедельник', 'во вторник', 'в среду', 'в четверг', 'в пятницу', 'в субботу'],
      at: 'в',
    },
    hero: {
      h1: ['Берёмся за случаи, ', 'от которых отказались', ' в других клиниках.'],
      lead: 'Импланты при нехватке кости, сложные восьмёрки, восстановление всей улыбки. Прежде чем что-то делать, показываем на снимке и объясняем.',
      place: 'Валенсия · у Torres de Serranos · с 2018 года',
      langs: 'Говорим по-русски, по-испански и по-английски',
      startLabel: 'Что беспокоит?',
      photoAlt: 'Хирург Smile House с бинокулярами и налобным светом за работой',
    },
    voices: {
      title: 'Что рассказывают те, кто пришёл из другой клиники',
      ids: ['shein', 'bynkalo', 'khairova', 'pod'],
    },
    caseFile: {
      title: 'Имплант 10 мм там, где оставалось 2,5 мм кости',
      lead: 'Так врачи клиники разбирают свои случаи. Этот они опубликовали в Instagram вместе с томограммами.',
      steps: [
        { mm: '2,5', title: 'Что было', text: 'Под гайморовой пазухой, в области верхней семёрки, оставалось 2,5 мм кости. Имплант держался бы в кости лишь на четверть своей длины.' },
        { mm: '7,5', title: 'Что нужно было получить', text: 'Чтобы поставить имплант 10 мм, дно пазухи поднимают на 7,5 мм и не рвут при этом слизистую, которая её выстилает. Врачи называют это экстремальным синус-лифтингом.' },
        { mm: '10', title: 'Что сделали', text: 'Имплант 10 мм установлен. Такие случаи планируют по томограмме до операции и объясняют пациенту на том же снимке.' },
      ],
      before: 'Томограмма до', after: 'Томограмма после',
      unit: 'мм кости', source: 'Случай в Instagram', url: IG + 'DVt_z_YDooL/',
    },
    ba: {
      title: 'До и после',
      lead: 'Фото, опубликованные клиникой. Потяните линию, чтобы сравнить.',
      before: 'До', after: 'После', handle: 'Сравнить до и после',
      cases: [
        { id: 'wear', label: 'Сильная стираемость', note: 'При такой стираемости мало просто поставить виниры: нужно заново спроектировать, как смыкаются челюсти, и выбрать материал, который выдержит нагрузку.', url: IG + 'DVWPIBHDI9u/' },
        { id: 'metal', label: 'Металл и отсутствующие зубы', note: 'Не хватало зубов, стояли металлические реставрации. После диагностики и плана — виниры, форма, симметрия и естественный оттенок.', url: IG + 'DQt68YPDfVY/' },
      ],
      open: 'Смотреть в Instagram',
    },
    visit: {
      title: ['Сначала ', 'объясняем', '. Потом лечим.'],
      lead: 'С первого визита вы уходите с понятным диагнозом, планом и ценой. Решение за вами.',
      steps: [
        { t: 'Рассказываете, что беспокоит', d: 'В WhatsApp, по телефону или через сайт, в любое время. Если болит — так и напишите.' },
        { t: 'Смотрим и показываем вам', d: 'Осмотр, снимок или томограмма, 3D-сканер. Вы видите на экране то же, что и врач.' },
        { t: 'План и цена до начала', d: 'Варианты лечения, разница между материалами и сколько стоит каждый.' },
        { t: 'Начинаем, когда вы готовы', d: 'Без спешки и без оставшихся вопросов.' },
      ],
      quotes: ['anders', 'iglesia', 'garcia'],
      photoAlt: 'Врач Smile House разговаривает с пациентом в кресле',
    },
    lens: {
      title: 'Под увеличением',
      lead: 'То, что пациенты видят на приёме и упоминают в отзывах.',
      items: [
        { img: 'eyepiece', t: 'Стоматологический микроскоп', d: 'Для каналов и реставраций там, где глазом не видно.' },
        { img: 'scanner', t: '3D-сканер', d: 'Ваши зубы на экране за минуты, без слепочной массы.' },
        { img: 'lab', t: 'Своя лаборатория', d: 'Керамика, диоксид циркония, дисиликат лития. Эффекты наносят вручную.' },
        { img: 'xray', t: 'Планирование по снимкам', d: 'Снимки и томограммы перед каждой операцией.' },
      ],
      harvard: { t: 'Доклад в Гарварде', d: 'Команда представила свои случаи в Harvard School of Dental Medicine (Бостон) в июне 2026 года.', alt: 'Команда Smile House в Harvard School of Dental Medicine' },
    },
    team: {
      title: 'Кто вас примет',
      lead: 'Врачи, которых пациенты называют по имени в отзывах Google.',
      doctors: [
        { id: 'dmitry', name: 'Дмитрий', role: 'Хирургия, имплантация, зубы мудрости', review: 'shein' },
        { id: 'javier', name: 'Хавьер', role: 'Лечение каналов', review: 'iglesia' },
        { id: 'lucila', name: 'Лусила', role: 'Терапия', review: 'magris' },
      ],
      photoAlt: 'Врач и ассистент Smile House работают с микроскопом',
    },
    services: {
      title: 'Лечение',
      lead: 'Цена — после консультации, письменно и до начала лечения.',
      consult: 'Цена на консультации',
      book: 'Записаться',
      items: [
        { key: 'implant', t: 'Импланты и синус-лифтинг', d: 'В том числе при нехватке кости. Планирование по томограмме.' },
        { key: 'wisdom', t: 'Зубы мудрости и сложные удаления', d: 'Наклонённые, у нерва, те, за которые другие не взялись.' },
        { key: 'veneers', t: 'Виниры, коронки, восстановление улыбки', d: 'Керамика, цирконий, дисиликат лития из нашей лаборатории.' },
        { key: 'endo', t: 'Каналы под микроскопом', d: 'Лечение и перелечивание каналов.' },
        { key: 'ortho', t: 'Ортодонтия', d: 'Брекеты, элайнеры, капы.' },
        { key: 'hygiene', t: 'Гигиена и отбеливание', d: 'Профессиональная чистка, отбеливание в клинике или дома.' },
        { key: 'urgent', t: 'Острая боль', d: 'Напишите, что болит, — скажем, когда сможем принять.' },
      ],
    },
    reviews: {
      title: 'Словами пациентов',
      lead: 'Дословные цитаты из отзывов в Google Maps.',
      all: 'Все отзывы в Google',
      ids: ['daniel', 'fatyuk', 'cotua', 'almudena', 'rl', 'barrera', 'medina', 'garcia'],
      source: 'Google',
    },
    faq: {
      title: 'О чём обычно спрашивают',
      items: [
        { q: 'Сколько стоит?', a: 'Зависит от случая, поэтому фиксированных цен на сайте нет. На первом визите вы получаете план и цену каждого варианта — до начала лечения.' },
        { q: 'Болит прямо сейчас. Примете быстро?', a: 'Напишите в WhatsApp или запишитесь с пометкой «Болит». Скажем, когда сможем принять. Пациенты с острой болью пишут в Google, что их приняли на следующий день.' },
        { q: 'Я боюсь стоматологов.', a: 'Об этом чаще всего и пишут в отзывах. До начала мы объясняем, что и зачем будем делать, и не начинаем, пока вам не станет понятно.' },
        { q: 'В другой клинике сказали, что ничего не сделать.', a: 'Принесите снимки или томограмму, если есть. Посмотрим и честно скажем, что можно сделать, а что нет.' },
        { q: 'Можно записаться к конкретному врачу?', a: 'Да, укажите при записи, и мы подтвердим, кто вас примет.' },
        { q: 'На каких языках говорите?', a: 'Русский, испанский, английский.' },
        { q: 'Где припарковаться?', a: 'Рядом с клиникой есть парковка, а из центра можно дойти пешком через Torres de Serranos.' },
      ],
    },
    contact: {
      title: 'У Torres de Serranos',
      near: 'По ту сторону моста, в районе La Zaidía. Рядом парковка, из центра можно дойти пешком.',
      hoursTitle: 'Часы работы', weekdays: 'Понедельник — пятница', weekend: 'Суббота и воскресенье', closedWord: 'Выходной',
      offHours: 'В нерабочее время пишите — ответим, как откроемся.',
      route: 'Маршрут', mapShow: 'Показать карту', mapConsent: 'Карту загружает Google, он может использовать cookies.',
    },
    booking: {
      title: 'Записаться',
      lead: 'Отметьте, что подходит. Откроется WhatsApp с готовым сообщением — останется отправить.',
      reason: 'Повод', day: 'Удобный день', time: 'Время', doctor: 'Врач', name: 'Ваше имя', note: 'Что-то ещё (необязательно)',
      notePh: 'Например: есть томограмма из другой клиники',
      reasons: [
        { k: 'urgent', l: 'Болит' }, { k: 'checkup', l: 'Первая консультация' }, { k: 'implant', l: 'Имплант' },
        { k: 'wisdom', l: 'Зуб мудрости' }, { k: 'veneers', l: 'Виниры, эстетика' }, { k: 'endo', l: 'Каналы' },
        { k: 'ortho', l: 'Ортодонтия' }, { k: 'hygiene', l: 'Чистка, отбеливание' },
      ],
      anyDay: 'Любой день', asap: 'Как можно скорее',
      times: [{ k: 'm', l: '10:00–12:00' }, { k: 'n', l: '12:00–14:00' }, { k: 'a', l: '14:00–16:30' }, { k: 'x', l: 'Не важно' }],
      anyDoctor: 'Любой',
      consent: 'Согласен(на), чтобы Smile House использовала эти данные для записи.',
      privacy: 'Конфиденциальность',
      send: 'Отправить в WhatsApp', orCall: 'или позвоните',
      errReason: 'Выберите повод.', errName: 'Напишите имя.', errConsent: 'Отметьте согласие, чтобы продолжить.',
      msg: { hello: 'Здравствуйте! Хочу записаться в Smile House.', reason: 'Повод', day: 'День', time: 'Время', doctor: 'Врач', name: 'Имя', note: 'Комментарий', lang: 'Язык', langVal: 'русский' },
      weekdayShort: ['вс', 'пн', 'вт', 'ср', 'чт', 'пт', 'сб'],
      months: ['янв', 'фев', 'мар', 'апр', 'мая', 'июн', 'июл', 'авг', 'сен', 'окт', 'ноя', 'дек'],
    },
    footer: {
      since: 'Стоматология в Валенсии с 2018 года',
      registro: 'Nº Registro Sanitario', registroPending: 'уточняется',
      legal: 'Правовая информация', cookies: 'Cookies', madeBy: 'Сайт: 2BRO.LAB',
    },
    cookie: { text: 'Без рекламных и аналитических cookies. Карта Google загрузится, только если вы разрешите.', accept: 'Разрешить карту', reject: 'Только необходимые', more: 'Подробнее' },
    translated: 'Перевод',
  },

  en: {
    htmlLang: 'en',
    ogLocale: 'en_GB',
    path: '/en/',
    meta: {
      title: 'Dentist in Valencia for complex cases | Smile House',
      description:
        'Smile House dental clinic by Torres de Serranos, Valencia. Implants with little bone, difficult wisdom teeth, veneers and full-mouth work. We show you on the scan and explain first. English, Spanish and Russian.',
    },
    langName: 'English',
    skip: 'Skip to content',
    nav: { cases: 'Cases', visit: 'First visit', team: 'Dentists', reviews: 'Reviews', contact: 'Find us', menu: 'Menu', close: 'Close' },
    cta: { book: 'Book a visit', whatsapp: 'WhatsApp', call: 'Call' },
    status: {
      open: 'Open', until: 'until', closed: 'Closed', opens: 'opens',
      today: 'today', tomorrow: 'tomorrow',
      days: ['on Sunday', 'on Monday', 'on Tuesday', 'on Wednesday', 'on Thursday', 'on Friday', 'on Saturday'],
      at: 'at',
    },
    hero: {
      h1: ['The cases ', 'other clinics refer on', ', we treat here.'],
      lead: 'Implants with little bone left, difficult wisdom teeth, whole smiles to rebuild. Before we touch anything, we show you on the scan and explain.',
      place: 'Valencia · by Torres de Serranos · since 2018',
      langs: 'We speak English, Spanish and Russian',
      startLabel: 'What brings you in?',
      photoAlt: 'Smile House surgeon at work with loupes and a headlight',
    },
    voices: {
      title: 'What patients who came from another clinic say',
      ids: ['shein', 'bynkalo', 'khairova', 'pod'],
    },
    caseFile: {
      title: 'A 10 mm implant where 2.5 mm of bone was left',
      lead: 'This is how the clinic’s dentists explain their cases. They published this one on Instagram with their own CT scans.',
      steps: [
        { mm: '2.5', title: 'What was there', text: 'Under the maxillary sinus, at the upper second molar, 2.5 mm of bone was left. An implant would be anchored in bone along only a quarter of its length.' },
        { mm: '7.5', title: 'What had to be gained', text: 'A 10 mm implant needs the sinus floor raised by 7.5 mm without tearing the membrane that lines it. Dentists call this an extreme sinus lift.' },
        { mm: '10', title: 'What was done', text: '10 mm implant placed. Cases like this are planned on a CT scan before surgery and explained to the patient on the same image.' },
      ],
      before: 'CT scan before', after: 'CT scan after',
      unit: 'mm of bone', source: 'See the case on Instagram', url: IG + 'DVt_z_YDooL/',
    },
    ba: {
      title: 'Before and after',
      lead: 'Photos published by the clinic. Drag the line to compare.',
      before: 'Before', after: 'After', handle: 'Compare before and after',
      cases: [
        { id: 'wear', label: 'Severe wear', note: 'With wear like this, veneers alone are not enough: the bite has to be redesigned and the material chosen to take the load.', url: IG + 'DVWPIBHDI9u/' },
        { id: 'metal', label: 'Metal crowns and gaps', note: 'Missing teeth and metal restorations. After diagnosis and planning: veneers, shape, symmetry and a natural shade.', url: IG + 'DQt68YPDfVY/' },
      ],
      open: 'See on Instagram',
    },
    visit: {
      title: ['First we ', 'explain', '. Then we treat.'],
      lead: 'You leave the first visit with a clear diagnosis, a plan and a price. The decision is yours.',
      steps: [
        { t: 'Tell us what’s wrong', d: 'On WhatsApp, by phone or through this site, any time. If it hurts, say so.' },
        { t: 'We look and show you', d: 'Examination, X-ray or CT scan and 3D scanner. You see on screen what we see.' },
        { t: 'Plan and price before we start', d: 'The options, the difference between materials and what each one costs.' },
        { t: 'We start when you’re ready', d: 'No rush and no open questions.' },
      ],
      quotes: ['iglesia', 'anders', 'garcia'],
      photoAlt: 'Smile House dentist talking to a patient in the chair',
    },
    lens: {
      title: 'Under magnification',
      lead: 'What patients see in the surgery and mention in their reviews.',
      items: [
        { img: 'eyepiece', t: 'Dental microscope', d: 'For root canals and restorations where the eye alone can’t see.' },
        { img: 'scanner', t: '3D scanner', d: 'Your teeth on screen in minutes, no impression paste.' },
        { img: 'lab', t: 'In-house lab', d: 'Ceramic, zirconia and lithium disilicate. Effects are painted by hand.' },
        { img: 'xray', t: 'Planning on the scan', d: 'X-rays and CT scans before every surgery.' },
      ],
      harvard: { t: 'Cases presented at Harvard', d: 'The team presented their cases at the Harvard School of Dental Medicine (Boston) in June 2026.', alt: 'Smile House team at the Harvard School of Dental Medicine' },
    },
    team: {
      title: 'Who will see you',
      lead: 'The dentists patients name in their Google reviews.',
      doctors: [
        { id: 'dmitry', name: 'Dr Dmitry', role: 'Oral surgery, implants, wisdom teeth', review: 'shein' },
        { id: 'javier', name: 'Dr Javier', role: 'Root canal treatment', review: 'iglesia' },
        { id: 'lucila', name: 'Dr Lucila', role: 'General dentistry', review: 'magris' },
      ],
      photoAlt: 'Smile House dentist and assistant working with the microscope',
    },
    services: {
      title: 'Treatments',
      lead: 'Price after the consultation, in writing, before we start.',
      consult: 'Priced at consultation',
      book: 'Book',
      items: [
        { key: 'implant', t: 'Implants and sinus lift', d: 'Including when little bone is left. Planned on a CT scan.' },
        { key: 'wisdom', t: 'Wisdom teeth and complex extractions', d: 'Tilted, near the nerve, the ones others preferred not to take out.' },
        { key: 'veneers', t: 'Veneers, crowns, full-mouth work', d: 'Ceramic, zirconia and lithium disilicate from our lab.' },
        { key: 'endo', t: 'Root canals under the microscope', d: 'First treatment and re-treatment.' },
        { key: 'ortho', t: 'Orthodontics', d: 'Braces, aligners and splints.' },
        { key: 'hygiene', t: 'Hygiene and whitening', d: 'Professional cleaning, in-clinic or at-home whitening.' },
        { key: 'urgent', t: 'Acute pain', d: 'Message us and say it hurts: we’ll tell you when we can see you.' },
      ],
    },
    reviews: {
      title: 'In patients’ words',
      lead: 'Verbatim quotes from Google Maps reviews.',
      all: 'All reviews on Google',
      ids: ['daniel', 'fatyuk', 'cotua', 'almudena', 'rl', 'barrera', 'medina', 'garcia'],
      source: 'Google',
    },
    faq: {
      title: 'What people usually ask',
      items: [
        { q: 'How much does it cost?', a: 'It depends on the case, so we don’t publish fixed prices. At the first visit you get the plan with the price of each option, before any treatment starts.' },
        { q: 'I’m in pain right now. Can you see me soon?', a: 'Message us on WhatsApp or book with “I’m in pain” ticked. We’ll tell you when we can see you. Patients with acute pain write on Google that they were seen the next day.' },
        { q: 'I’m scared of dentists.', a: 'It’s what reviews mention most. Before starting we explain what we’ll do and why, and nothing starts until it’s clear to you.' },
        { q: 'Another clinic told me nothing can be done.', a: 'Bring your X-rays or CT scan if you have them. We’ll look and tell you honestly what can and can’t be done.' },
        { q: 'Can I book with a specific dentist?', a: 'Yes, say so when you book and we’ll confirm who will see you.' },
        { q: 'Which languages do you speak?', a: 'English, Spanish and Russian.' },
        { q: 'Where can I park?', a: 'There is parking near the clinic, and from the centre it’s a walk across Torres de Serranos.' },
      ],
    },
    contact: {
      title: 'By Torres de Serranos',
      near: 'Across the bridge, in La Zaidía. Parking nearby; walking distance from the centre.',
      hoursTitle: 'Opening hours', weekdays: 'Monday to Friday', weekend: 'Saturday and Sunday', closedWord: 'Closed',
      offHours: 'Out of hours? Message us and we’ll reply when we open.',
      route: 'Directions', mapShow: 'Show the map', mapConsent: 'The map is loaded by Google and may use cookies.',
    },
    booking: {
      title: 'Book a visit',
      lead: 'Pick what fits. WhatsApp opens with the message ready; you just send it.',
      reason: 'Reason', day: 'Day that suits you', time: 'Time', doctor: 'Dentist', name: 'Your name', note: 'Anything else (optional)',
      notePh: 'For example: I have a CT scan from another clinic',
      reasons: [
        { k: 'urgent', l: 'I’m in pain' }, { k: 'checkup', l: 'First consultation' }, { k: 'implant', l: 'Implant' },
        { k: 'wisdom', l: 'Wisdom tooth' }, { k: 'veneers', l: 'Veneers, aesthetics' }, { k: 'endo', l: 'Root canal' },
        { k: 'ortho', l: 'Orthodontics' }, { k: 'hygiene', l: 'Cleaning, whitening' },
      ],
      anyDay: 'Any day', asap: 'As soon as possible',
      times: [{ k: 'm', l: '10:00–12:00' }, { k: 'n', l: '12:00–14:00' }, { k: 'a', l: '14:00–16:30' }, { k: 'x', l: 'No preference' }],
      anyDoctor: 'Any',
      consent: 'I agree that Smile House may use this data to book my visit.',
      privacy: 'Privacy',
      send: 'Send on WhatsApp', orCall: 'or call',
      errReason: 'Choose a reason.', errName: 'Add your name.', errConsent: 'Tick the box to continue.',
      msg: { hello: 'Hello, I’d like to book a visit at Smile House.', reason: 'Reason', day: 'Day', time: 'Time', doctor: 'Dentist', name: 'Name', note: 'Note', lang: 'Language', langVal: 'English' },
      weekdayShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
      months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    },
    footer: {
      since: 'Dental clinic in Valencia since 2018',
      registro: 'Nº Registro Sanitario', registroPending: 'pending',
      legal: 'Legal notice and privacy', cookies: 'Cookies', madeBy: 'Site: 2BRO.LAB',
    },
    cookie: { text: 'No advertising or analytics cookies. The Google map only loads if you allow it.', accept: 'Allow map', reject: 'Necessary only', more: 'More info' },
    translated: 'Translation',
  },
};

export const langs = ['es', 'ru', 'en'];
